### ISSUE TITLE
Issue with XTRegisterSameChannel.py

### ISSUE THREAD

**Issue by linjing-fang** [niaid/imaris_extensions#26] opened 2021-11-04 21:02 UTC
Hi! 

Thank you first for your cool work and the tremendous effort for the user-friendly GUI and great documentation. 

I ran into no issues when using the XTRegisterSameChannel.py extension until the 'Resample And Save Combined Image' step. Please find the error message below. I was wondering if you ever encounter a similar issue before and perhaps know the solution? Thank you very much!

Exception occurred during computation:
Traceback (most recent call last):
  File "C:\Users\BIF users_New\Downloads\imaris_extensions-main\imaris_extensions-main\XTRegisterSameChannel.py", line 1184, in run
    sio.write(resampled_image, self.output_file_name)
  File "C:\Users\BIF users_New\Downloads\imaris_extensions-main\imaris_extensions-main\sitk_ims_file_io.py", line 1026, in write
    _write_channel_histogram(grp, channel_arr_view, channel.GetPixelID())
  File "C:\Users\BIF users_New\Downloads\imaris_extensions-main\imaris_extensions-main\sitk_ims_file_io.py", line 1061, in _write_channel_histogram
    compression_opts=2,
  File "C:\ProgramData\Anaconda3\envs\imaris\lib\site-packages\h5py\_hl\group.py", line 148, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "C:\ProgramData\Anaconda3\envs\imaris\lib\site-packages\h5py\_hl\dataset.py", line 137, in make_new_dset
    dset_id = h5d.create(parent.id, name, tid, sid, dcpl=dcpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5d.pyx", line 87, in h5py.h5d.create
ValueError: Unable to create dataset (name already exists)

Best,
Lynn

**Comment by zivy** [comment] 2021-11-04 23:11
Hello @linjing-fang,

Looks like you uncovered a bug in code committed yesterday #24 . If you are using git (didn't download the repository using the zip file), you can easily revert to the previous version that works, `git checkout HEAD~2`. 

Will post an update here once the issue is resolved.

**Comment by linjing-fang** [comment] 2021-11-04 23:39
> Hello @linjing-fang,
> 
> Looks like you uncovered a bug in code committed yesterday #24 . If you are using git (didn't download the repository using the zip file), you can easily revert to the previous version that works, `git checkout HEAD~2`.
> 
> Will post an update here once the issue is resolved.

Wow thanks so much for the prompt reply! I'll do so :)

**Comment by linjing-fang** [comment] 2021-11-05 00:25
Update: The issue can be solved by reverting to the previous commit as instructed. Thanks again!

**Comment by zivy** [comment] 2021-11-05 12:30
Re-opening. Will close once the issue is really resolved. Reversion is just a workaround.

**Comment by zivy** [comment] 2021-11-09 00:51
Hello @linjing-fang,

Please update the code you have with the latest from GitHub, addresses this issue, and confirm that the updated code works for you.

**Comment by linjing-fang** [comment] 2021-11-12 01:40
> Hello @linjing-fang,
> 
> Please update the code you have with the latest from GitHub, addresses this issue, and confirm that the updated code works for you.

Hi! I got the chance to pull the change and rerun the same pipeline. It works smoothly on a win10 workstation (I had trouble creating the conda env in a Macbook Pro M1, specifically i was struggling with installing PySide2 with pip. I can report the error message if you are interested, but it might be just a problem uniquely to the M1 chip). Thanks again for the quick fix!

Apologies if I should have opened a new issue, but I just wanted to throw a quick question here, is it possible to specify the number of blocks in x and y when calculating the cross correlations before and after the registration? My image is a big montage stitched from 6x3 tile scans. It would be nice if I could specify the blocks to be 6x3 so each block of the output heatmap corresponds to the original tile. Thank you!

**Comment by zivy** [comment] 2021-11-12 14:35
Hello @linjing-fang,

M1 is relatively new, so it has created a lot of issues for many libraries. SimpleITK started supporting M1 only four months ago in [release 2.1.0](https://github.com/SimpleITK/SimpleITK/releases/tag/v2.1.0). I suspect this type of problem will go away over time.

The cross correlations are computed using the whole image, which is what the registration framework uses. It reflects the values obtained using the final transformation. Defining regions of interest is outside the scope of this extension. Having said that, you can easily play with this yourself (assuming here you are comfortable with Python). The code to do it is pretty simple and can be based on the [existing function](https://github.com/niaid/imaris_extensions/blob/4bbc17e102cc8ff0db5fb2995d5b94976c0a1d6d/XTRegisterSameChannel.py#L732-L748). Read all the relevant channels from the output file, call [numpy corrcoef](https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html) using the data from the region of interest you define.

Will close this issue now as the original problem was solved. If you have additional questions, please open a dedicated issue.

**Closed by zivy** 2021-11-12 14:35 UTC
Labels: bug report, confirmed bug

**Comment by linjing-fang** [comment] 2021-11-12 16:02
> Hello @linjing-fang,
> 
> M1 is relatively new, so it has created a lot of issues for many libraries. SimpleITK started supporting M1 only four months ago in [release 2.1.0](https://github.com/SimpleITK/SimpleITK/releases/tag/v2.1.0). I suspect this type of problem will go away over time.
> 
> The cross correlations are computed using the whole image, which is what the registration framework uses. It reflects the values obtained using the final transformation. Defining regions of interest is outside the scope of this extension. Having said that, you can easily play with this yourself (assuming here you are comfortable with Python). The code to do it is pretty simple and can be based on the [existing function](https://github.com/niaid/imaris_extensions/blob/4bbc17e102cc8ff0db5fb2995d5b94976c0a1d6d/XTRegisterSameChannel.py#L732-L748). Read all the relevant channels from the output file, call [numpy corrcoef](https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html) using the data from the region of interest you define.
> 
> Will close this issue now as the original problem was solved. If you have additional questions, please open a dedicated issue.

This is very helpful. Thank you!!
